name: test-workflow

on:
  push:

jobs:
  test_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR title
        run: |
          if [[ "${{ github.event.pull_request.title }}" =~ ^octocat ]]; then
          echo "PR title starts with 'octocat'"
          exit 0
          else
          echo "PR title did not start with 'octocat'"
          exit 1
          fi
